<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title></title>
  </head>
  <body>
    <script>
      // normal function.
      function first() {
        console.log("First");
      }
      // function second() and passing third() as callback.
      function second(callback) {
        // code within setTimeout() will run after 1 sec.
        setTimeout(() => {
          console.log("second.");
          // calling third() and passing  fourth() as callback..
          callback(forth);
        }, 1000);
      }

      // function third() and passing fourth() as callback.
      function third(callback) {
        // This block of code will  be executed after 2 sec.
        setTimeout(() => {
          console.log("third");
          // calling fourth() and passing fifth() as callback.
          callback(fifth);
        }, 2000);
      }
      // function fourth() and passing fifth() as callback.
      function forth(callback) {
        setTimeout(() => {
          console.log("fourth");
          callback();
        }, 3000);
      }

      function fifth() {
        // This  block of code will run after 2 sec.
        setTimeout(() => {
          console.log("fifth");
        }, 2000);
      }
      first();
      // asynchronous function call - after second() is executed, third() will be called.
      second(third);

      // Callback hell:Nesting of calls makes it difficult to handle errors and debugging.
      function callbackHell() {
        setTimeout(() => {
          console.log("This is callback hell 1!");
          setTimeout(() => {
            console.log("This is callback hell 2!");
            setTimeout(() => {
              console.log("This is callback hell 3!");
            }, 6000);
          }, 4000);
        }, 4000);
      }
      callbackHell();
    </script>
    <script>
      // function returning a  promise.
      function getUsers(onSuccess) {
        return new Promise((resolve, reject) => {
          if (onSuccess) {
            resolve([
              { id: 1, name: "Jerry" },
              { id: 2, name: "Elaine" },
              { id: 3, name: "George" },
            ]);
          } else {
            reject("Failed to fetch.");
          }
        }, 1000);
      }
      // Success case
      getUsers(true)
        .then((response) => {
          console.log(response);
        })
        .catch((error) => {
          console.log(error);
        });
    </script>
    <script>
      function fetchData(callback) {
        // asynchronous code which will run after 2 sec.
        setTimeout(() => {
          const data = [1, 2, 3, 4, 5];
          callback(data);
        }, 2000);
      }
      function getData(data) {
        console.log(data.map((key) => key * 2));
      }
      // function call and passing callback function.
      fetchData(getData);
    </script>
    <script>
      // function returning a promise: nor resolved nor rejected.
      function fetchData() {
        return new Promise((resolve, reject) => {
          setTimeout(() => {
            const data = [{ name: "John", age: 22 }];
          }, 7000);
        });
      }
      // The promise is not resolved  nor rejected: hence it will be in pending state.
      fetchData()
        .then((data) => {
          console.log(data);
        })
        .catch((error) => {
          console.log(error, 200);
        });
    </script>
  </body>
</html>
