<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Promises</title>
  </head>
  <body>
    <script>
      const ticket = new Promise(function (resolve, reject) {
        const isBoarded = true;
        if (isBoarded) {
          resolve("You are in the flight");
        } else {
          reject("Your flight has been cancelled");
        }
      });

      ticket
        .then((data) => {
          console.log("wohooo", data);
        })
        .catch((data) => {
          console.log("Oh no", data);
        })
        .finally(() => {
          console.log("I will always be executed.");
        });
    </script>
    <script>
      // Making a pizza:    cheese => dough => pizza
      function getCheese() {
        return new Promise((resolve, reject) => {
          setTimeout(() => {
            const cheese = "🧀";

            resolve(cheese);
          }, 2000);
        });
      }

      function makeDough(cheese) {
        return new Promise((resolve, reject) => {
          setTimeout(() => {
            const dough = cheese + "🍪";

            resolve(dough);
          }, 2000);
        });
      }

      function makePizza(dough) {
        return new Promise((resolve, reject) => {
          setTimeout(() => {
            const pizza = dough + "🍕";
            resolve(pizza);
          }, 2000);
        });
      }
      getCheese()
        .then((cheese) => {
          console.log("Here is the : ", cheese);
          return makeDough(cheese);
        })
        .then((dough) => {
          console.log("Here is the: ", dough);
          return makePizza(dough);
        })
        .then((pizza) => {
          console.log("Here is the: ", pizza);
        })
        // If problem occurs in any of the above, it will execute the  catch block
        .catch((data) => {
          console.log("Error occurred : ", data);
        })
        .finally(() => {
          console.log("Process ended");
        });

      /**
       * The  above execution using async/await
       **/
      async function orderPizza() {
        try {
          const cheese = await getCheese();
          console.log("Here is  the cheese");
          const dough = await makeDough(cheese);
          console.log("Here is the dough");
          const pizza = await makePizza(dough);
          console.log("Here is the pizza.");
        } catch (error) {
          console.log("Error occurred: ", error);
        } finally {
          console.log("Process ended!");
        }
      }
      orderPizza();
    </script>
  </body>
</html>
